steps:
  # Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_SERVICE_NAME:$SHORT_SHA",
        "--build-arg",
        "COMMIT_SHA=$COMMIT_SHA",
        ".",
      ]

  # Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_SERVICE_NAME:$SHORT_SHA",
      ]

  # Deploy
  - name: "gcr.io/cloud-builders/gcloud-slim"
    id: trigger-deployment
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$_SERVICE_NAME"
      - "--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
      - "--region=$_REGION"
      - "--project=$PROJECT_ID"
      - "--max-instances=$_MAX_INSTANCES"
      - "--cpu-boost"
      - "--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=$_LOCATION,LOG_LEVEL=$_LOG_LEVEL,APP_NAME=$_APP_NAME,AGENT_NAME=$_AGENT_NAME,GOOGLE_GENAI_USE_VERTEXAI=$_GOOGLE_GENAI_USE_VERTEXAI,MODEL=$_MODEL"
      - "--service-account=$_APP_SERVICE_ACCOUNT"
      - "--allow-unauthenticated" # Allow unauthenticated invocations - end user will perform OAuth

logsBucket: gs://${_LOGS_BUCKET_NAME_PROD}/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: "europe-west1"
  _LOCATION: "global"
  _SERVICE_NAME: "dazbo-portfolio"
  _APP_NAME: "dazbo_portfolio"
  _AGENT_NAME: "dazbo_portfolio_chat_agent"
  _GOOGLE_GENAI_USE_VERTEXAI: "True"
  _MODEL: "gemini-3-flash-preview"
  _MAX_INSTANCES: "1"
  _LOG_LEVEL: INFO
  _APP_SERVICE_ACCOUNT: $_SERVICE_NAME-app@${PROJECT_ID}.iam.gserviceaccount.com
  _LOGS_BUCKET_NAME_PROD: "${PROJECT_ID}-logs"

