steps:
  # Install uv package manager and sync dependencies
  - name: "python:3.12-slim"
    id: install-dependencies
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        pip install uv==0.8.13 --user && uv sync --locked
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  # Run unit tests using pytest
  - name: "python:3.12-slim"
    id: unit-tests
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        uv run pytest tests/unit
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'
      - 'CI=true'

  # Run integration tests
  - name: "python:3.12-slim"
    id: integration-tests
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        uv run pytest tests/integration
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'
      - 'CI=true'
      - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID}'
      - 'GOOGLE_CLOUD_LOCATION=global'
      - 'GOOGLE_GENAI_USE_VERTEXAI=true'

logsBucket: gs://${PROJECT_ID}-logs/build-logs
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
